import { AiFillInstagram, AiFillSafetyCertificate } from "react-icons/ai"
import {
  FaAngleRight,
  FaAward,
  FaBoxOpen,
  FaDev,
  FaFacebookF,
  FaGithub,
  FaGithubAlt,
  FaHeart,
  FaInfoCircle,
  FaInstagram,
  FaLink,
  FaLinkedinIn,
  FaPaintBrush,
  FaSignLanguage,
  FaStar,
  FaHome,
  FaAngleDoubleUp
} from "react-icons/fa"
import { GoTools } from "react-icons/go"
import {
  IoIosDocument,
  IoIosJournal,
  IoIosMoon,
  IoIosPaperPlane,
  IoIosSunny,
  IoIosRocket
} from "react-icons/io"
import {
  MdLocationOn,
  MdMenu,
  MdMoreHoriz,
  MdPerson,
  MdSchool,
  MdWork,
  MdMusicNote,
} from "react-icons/md"

export {
  AiFillInstagram,
  AiFillSafetyCertificate,
  FaAngleRight,
  FaAward,
  FaBoxOpen,
  FaDev,
  FaFacebookF,
  FaGithub,
  FaGithubAlt,
  FaHeart,
  FaInfoCircle,
  FaInstagram,
  FaLink,
  FaLinkedinIn,
  FaPaintBrush,
  FaSignLanguage,
  FaStar,
  GoTools,
  IoIosDocument,
  IoIosJournal,
  IoIosMoon,
  IoIosPaperPlane,
  IoIosSunny,
  IoIosRocket,
  MdLocationOn,
  MdMenu,
  MdMoreHoriz,
  MdPerson,
  MdSchool,
  MdWork,
  MdMusicNote,
  FaHome,
  FaAngleDoubleUp,
}
